apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=cac68212f0ab5b9f5d6d24a5f47fcc56a8aecad7
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:a49d7c0b2fde4d617eae055d265db7c90c402e2a@sha256:7b28e9399a228f7efb463c785af6d6ee6fbb7844026656b551fa8770e4fb0d5c
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=a49d7c0b2fde4d617eae055d265db7c90c402e2a
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
images:
  - name: quay.io/redhat-appstudio/enterprise-contract-controller
    newName: quay.io/redhat-appstudio/enterprise-contract-controller
    newTag: cac68212f0ab5b9f5d6d24a5f47fcc56a8aecad7
