apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-attestation-signature
spec:
  params:
    - name: TASK_LABEL
      type: string
      description: The label to identify the task
      default:  kaniko-chains
  steps:
    - name: cosign-verify
      image: quay.io/jstuart/appstudio-utils:latest
      command: ["bash"]
      args: ["/appstudio-utils/util-scripts/tekton-chains/kaniko-cosign-verify-task.sh", "$(params.TASK_LABEL)"]
