resources:
- gitops.yaml
- build.yaml
- authentication.yaml
- has.yaml
- release.yaml
- spi.yaml
- e2e-tests.yaml
- infra-deployments-ci.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
