apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: infra-deployments-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
        type: string
      - name: revision
        type: string
    tasks:
      - name: git-clone
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        taskRef:
          kind: ClusterTask
          name: git-clone
        workspaces:
          - name: output
            workspace: source
      - name: test-tekton-chains
        runAfter:
          - git-clone
        taskRef:
          kind: ClusterTask
          name: verify-taskrun-signature
        workspaces:
          - name: source
            workspace: source
    workspaces:
      - name: source
  serviceAccountName: pipeline
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: infra-deployments-{{revision}}