apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitops-service-cluster-agent
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitops-service-cluster-agent-
        annotations:
          github.integrations.tekton.dev/commit: $(tt.params.git-revision)
          github.integrations.tekton.dev/owner: $(tt.params.pusher-name)
          github.integrations.tekton.dev/repo: infra-deployments
          github.integrations.tekton.dev/repo-url: "$(tt.params.pusher-name)/infra-deployments"
      spec:
        params:
          - name: git-url
            value: 'https://github.com/redhat-appstudio/managed-gitops'
          - name: revision
            value: $(tt.params.git-revision)
          - name: output-image
            value: 'quay.io/redhat-appstudio/gitops-service:$(tt.params.git-revision)'
          - name: path-context
            value: .
          - name: dockerfile
            value: Dockerfile
        pipelineRef:
          name: basic-build
          bundle: quay.io/jstuart/build-templates-bundle:latest
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: app-studio-default-workspace
            subPath: gitops-service-$(tt.params.git-revision)
