apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitops-service-cluster-agent
spec:
  params:
    - name: pullreq-sha
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitops-service-cluster-agent-
        annotations:
          github.integrations.tekton.dev/commit: $(tt.params.pullreq-sha)
          github.integrations.tekton.dev/repo-url: $(tt.params.git-repo-url)
      spec:
        params:
          - name: git-url
            value: 'https://github.com/redhat-appstudio/managed-gitops'
          - name: revision
            value: $(tt.params.pullreq-sha)
          - name: output-image
            value: 'quay.io/redhat-appstudio/gitops-service:$(tt.params.pullreq-sha)'
          - name: path-context
            value: .
          - name: dockerfile
            value: Dockerfile
        pipelineRef:
          name: basic-build-init
          bundle: quay.io/jstuart/build-templates-bundle:latest
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: app-studio-default-workspace
            subPath: gitops-service-$(tt.params.pullreq-sha)
